gAbilityDescription_None: @ 81F99CC
	.string "Nenhuma habilidade especial.$"

gAbilityDescription_Stench: @ 81F99E0
	.string "Ajuda a repelir pokémon.$"

gAbilityDescription_Drizzle: @ 81F99FA
	.string "Invoca chuva na batalha.$"

gAbilityDescription_SpeedBoost: @ 81F9A12
	.string "Velocidade sobe por turno.$"

gAbilityDescription_BattleArmor: @ 81F9A2A
	.string "Bloqueia golpes críticos.$"

gAbilityDescription_Sturdy: @ 81F9A40
	.string "Nega golpes fatais.$"

gAbilityDescription_Damp: @ 81F9A5A
	.string "Evita a autodestruição.$"

gAbilityDescription_Limber: @ 81F9A75
	.string "Evita paralisia.$"

gAbilityDescription_SandVeil: @ 81F9A89
	.string "Evasão em tempestade areia.$"

gAbilityDescription_Static: @ 81F9AA5
	.string "Paraliza em contato.$"

gAbilityDescription_VoltAbsorb: @ 81F9ABB
	.string "Absorve a eletricidade.$"

gAbilityDescription_WaterAbsorb: @ 81F9AD6
	.string "Absorve a água.$"

gAbilityDescription_Oblivious: @ 81F9AED
	.string "Evita atração.$"

gAbilityDescription_CloudNine: @ 81F9B02
	.string "Nega efeitos climáticos.$"

gAbilityDescription_CompoundEyes: @ 81F9B1B
	.string "Aumenta precisão.$"

gAbilityDescription_Insomnia: @ 81F9B2C
	.string "Evita o sono.$"

gAbilityDescription_ColorChange: @ 81F9B3C
	.string "Muda tipo para golpe levado.$"

gAbilityDescription_Immunity: @ 81F9B58
	.string "Evita envenenamento.$"

gAbilityDescription_FlashFire: @ 81F9B6C
	.string "Fortalece com fogo.$"

gAbilityDescription_ShieldDust: @ 81F9B86
	.string "Impede efeitos adicionais.$"

gAbilityDescription_OwnTempo: @ 81F9B9E
	.string "Evita confusão.$"

gAbilityDescription_SuctionCups: @ 81F9BB2
	.string "Fixa firmemente o corpo.$"

gAbilityDescription_Intimidate: @ 81F9BCB
	.string "Reduz o ataque do inimigo.$"

gAbilityDescription_ShadowTag: @ 81F9BE4
	.string "Evita a fuga dos inimigos.$"

gAbilityDescription_RoughSkin: @ 81F9BFF
	.string "Machuca ao tocar.$"

gAbilityDescription_WonderGuard: @ 81F9C0F
	.string "“Golpes super efetivos.”$"

gAbilityDescription_Levitate: @ 81F9C27
	.string "Imune à golpes terrestres.$"

gAbilityDescription_EffectSpore: @ 81F9C42
	.string "Deixa esporos ao contato.$"

gAbilityDescription_Synchronize: @ 81F9C5C
	.string "Passa problemas de status.$"

gAbilityDescription_ClearBody: @ 81F9C77
	.string "Evita redução.$"

gAbilityDescription_NaturalCure: @ 81F9C93
	.string "Cura após trocar.$"

gAbilityDescription_LightningRod: @ 81F9CAD
	.string "Atrai golpes elétricos.$"

gAbilityDescription_SereneGrace: @ 81F9CC5
	.string "Promove efeitos adicionais.$"

gAbilityDescription_SwiftSwim: @ 81F9CDD
	.string "Mais velocidade na chuva.$"

gAbilityDescription_Chlorophyll: @ 81F9CF3
	.string "Eleva velocidade no sol.$"

gAbilityDescription_Illuminate: @ 81F9D0D
	.string "Atrai pokémons selvagens.$"

gAbilityDescription_Trace: @ 81F9D27
	.string "Copia a habilidade.$"

gAbilityDescription_HugePower: @ 81F9D3F
	.string "Aumenta ataque.$"

gAbilityDescription_PoisonPoint: @ 81F9D4E
	.string "Envenena em contato.$"

gAbilityDescription_InnerFocus: @ 81F9D66
	.string "Evita recuo.$"

gAbilityDescription_MagmaArmor: @ 81F9D7A
	.string "Evita congelamento.$"

gAbilityDescription_WaterVeil: @ 81F9D8D
	.string "Evita queimadura.$"

gAbilityDescription_MagnetPull: @ 81F9D9D
	.string "Atrai tipo metal.$"

gAbilityDescription_Soundproof: @ 81F9DB7
	.string "Evita golpes sonoros.$"

gAbilityDescription_RainDish: @ 81F9DD1
	.string "Recupera PV na chuva.$"

gAbilityDescription_SandStream: @ 81F9DED
	.string "Invoca tempestade de areia.$"

gAbilityDescription_Pressure: @ 81F9E02
	.string "Inimigo usa mais PG.$"

gAbilityDescription_ThickFat: @ 81F9E19
	.string "Protege do frio e calor.$"

gAbilityDescription_EarlyBird: @ 81F9E33
	.string "Acorda mais cedo.$"

gAbilityDescription_FlameBody: @ 81F9E4F
	.string "Queima em contato.$"

gAbilityDescription_RunAway: @ 81F9E69
	.string "Facilita a fuga.$"

gAbilityDescription_KeenEye: @ 81F9E80
	.string "Evita perda de precisão.$"

gAbilityDescription_HyperCutter: @ 81F9E9B
	.string "Evita redução de ataque.$"

gAbilityDescription_Pickup: @ 81F9EB6
	.string "Pode pegar ítens.$"

gAbilityDescription_Truant: @ 81F9EC9
	.string "Move a cada duas rodadas.$"

gAbilityDescription_Hustle: @ 81F9EE5
	.string "Troca precisão por poder.$"

gAbilityDescription_CuteCharm: @ 81F9F00
	.string "Apaixona em contato.$"

gAbilityDescription_Plus: @ 81F9F17
	.string "Poder aumenta com menos.$"

gAbilityDescription_Minus: @ 81F9F2D
	.string "Poder aumenta com mais.$"

gAbilityDescription_Forecast: @ 81F9F42
	.string "Muda com o tempo.$"

gAbilityDescription_StickyHold: @ 81F9F5C
	.string "Impede o roubo de itens.$"

gAbilityDescription_ShedSkin: @ 81F9F71
	.string "Cura status.$"

gAbilityDescription_Guts: @ 81F9F8D
	.string "Sobe ataque na dor.$"

gAbilityDescription_MarvelScale: @ 81F9FA6
	.string "Sobe defesa na dor.$"

gAbilityDescription_LiquidOoze: @ 81F9FC0
	.string "Drenagem causa ferimento.$"

gAbilityDescription_Overgrow: @ 81F9FD8
	.string "Sobe golpe grama na dor.$"

gAbilityDescription_Blaze: @ 81F9FF4
	.string "Sobe golpe fogo na dor.$"

gAbilityDescription_Torrent: @ 81FA00F
	.string "Sobe golpe água na dor.$"

gAbilityDescription_Swarm: @ 81FA02B
	.string "Sobe golpe inseto na dor.$"

gAbilityDescription_RockHead: @ 81FA045
	.string "Evita danos ao atacar.$"

gAbilityDescription_Drought: @ 81FA05D
	.string "Invoca sol forte.$"

gAbilityDescription_ArenaTrap: @ 81FA079
	.string "Evita fugas.$"

gAbilityDescription_VitalSpirit: @ 81FA08B
	.string "Evita dormir.$"

gAbilityDescription_WhiteSmoke: @ 81FA09B
	.string "Evita redução.$"

gAbilityDescription_PurePower: @ 81FA0B7
	.string "Aumenta ataque.$"

gAbilityDescription_ShellArmor: @ 81FA0C6
	.string "Bloqueia golpes críticos.$"

gAbilityDescription_Cacophony: @ 81FA0DC
	.string "Evita golpes sonoros.$"

gAbilityDescription_AirLock: @ 81FA0F6
	.string "Nega efeitos climáticos.$"

	.align 2
gAbilityDescriptions:: @ 81FA110
	.4byte gAbilityDescription_None
	.4byte gAbilityDescription_Stench
	.4byte gAbilityDescription_Drizzle
	.4byte gAbilityDescription_SpeedBoost
	.4byte gAbilityDescription_BattleArmor
	.4byte gAbilityDescription_Sturdy
	.4byte gAbilityDescription_Damp
	.4byte gAbilityDescription_Limber
	.4byte gAbilityDescription_SandVeil
	.4byte gAbilityDescription_Static
	.4byte gAbilityDescription_VoltAbsorb
	.4byte gAbilityDescription_WaterAbsorb
	.4byte gAbilityDescription_Oblivious
	.4byte gAbilityDescription_CloudNine
	.4byte gAbilityDescription_CompoundEyes
	.4byte gAbilityDescription_Insomnia
	.4byte gAbilityDescription_ColorChange
	.4byte gAbilityDescription_Immunity
	.4byte gAbilityDescription_FlashFire
	.4byte gAbilityDescription_ShieldDust
	.4byte gAbilityDescription_OwnTempo
	.4byte gAbilityDescription_SuctionCups
	.4byte gAbilityDescription_Intimidate
	.4byte gAbilityDescription_ShadowTag
	.4byte gAbilityDescription_RoughSkin
	.4byte gAbilityDescription_WonderGuard
	.4byte gAbilityDescription_Levitate
	.4byte gAbilityDescription_EffectSpore
	.4byte gAbilityDescription_Synchronize
	.4byte gAbilityDescription_ClearBody
	.4byte gAbilityDescription_NaturalCure
	.4byte gAbilityDescription_LightningRod
	.4byte gAbilityDescription_SereneGrace
	.4byte gAbilityDescription_SwiftSwim
	.4byte gAbilityDescription_Chlorophyll
	.4byte gAbilityDescription_Illuminate
	.4byte gAbilityDescription_Trace
	.4byte gAbilityDescription_HugePower
	.4byte gAbilityDescription_PoisonPoint
	.4byte gAbilityDescription_InnerFocus
	.4byte gAbilityDescription_MagmaArmor
	.4byte gAbilityDescription_WaterVeil
	.4byte gAbilityDescription_MagnetPull
	.4byte gAbilityDescription_Soundproof
	.4byte gAbilityDescription_RainDish
	.4byte gAbilityDescription_SandStream
	.4byte gAbilityDescription_Pressure
	.4byte gAbilityDescription_ThickFat
	.4byte gAbilityDescription_EarlyBird
	.4byte gAbilityDescription_FlameBody
	.4byte gAbilityDescription_RunAway
	.4byte gAbilityDescription_KeenEye
	.4byte gAbilityDescription_HyperCutter
	.4byte gAbilityDescription_Pickup
	.4byte gAbilityDescription_Truant
	.4byte gAbilityDescription_Hustle
	.4byte gAbilityDescription_CuteCharm
	.4byte gAbilityDescription_Plus
	.4byte gAbilityDescription_Minus
	.4byte gAbilityDescription_Forecast
	.4byte gAbilityDescription_StickyHold
	.4byte gAbilityDescription_ShedSkin
	.4byte gAbilityDescription_Guts
	.4byte gAbilityDescription_MarvelScale
	.4byte gAbilityDescription_LiquidOoze
	.4byte gAbilityDescription_Overgrow
	.4byte gAbilityDescription_Blaze
	.4byte gAbilityDescription_Torrent
	.4byte gAbilityDescription_Swarm
	.4byte gAbilityDescription_RockHead
	.4byte gAbilityDescription_Drought
	.4byte gAbilityDescription_ArenaTrap
	.4byte gAbilityDescription_VitalSpirit
	.4byte gAbilityDescription_WhiteSmoke
	.4byte gAbilityDescription_PurePower
	.4byte gAbilityDescription_ShellArmor
	.4byte gAbilityDescription_Cacophony
	.4byte gAbilityDescription_AirLock
