gAbilityNames:: @ 81FA248
	.string "-------$", 13
	.string "Fedor$", 13
	.string "Chuvisco$", 13
	.string "Acelerador$", 13
	.string "Traje Luta$", 13
	.string "Fortificar$", 13
	.string "Umidade$", 13
	.string "Elasticidade$", 13
	.string "Véu De Areia$", 13
	.string "Estática$", 13
	.string "Absorve Volt$", 13
	.string "Absorve Água$", 13
	.string "Inconsciente$", 13
	.string "Anti-Tempo$", 13
	.string "Olho Preciso$", 13
	.string "Insônia$", 13
	.string "Troca De Cor$", 13
	.string "Imunidade$", 13
	.string "Luz De Fogo$", 13
	.string "Escudo De Pó$", 13
	.string "Rítmo Único$", 13
	.string "Braço Sucção$", 13
	.string "Intimidar$", 13
	.string "Fio Sombrio$", 13
	.string "Pele Áspera$", 13
	.string "Super Defesa$", 13
	.string "Levitação$", 13
	.string "Efeito Pólen$", 13
	.string "Sincronia$", 13
	.string "Corpo Claro$", 13
	.string "Cura Natural$", 13
	.string "Para-Raios$", 13
	.string "Graça Serena$", 13
	.string "Nado Rápido$", 13
	.string "Clorofila$", 13
	.string "Iluminar$", 13
	.string "Traçar$", 13
	.string "Força Grande$", 13
	.string "Ponta Tóxica$", 13
	.string "Foco Interno$", 13
	.string "Traje Magma$", 13
	.string "Véu De Água$", 13
	.string "Magnetismo$", 13
	.string "Anti-Som$", 13
	.string "Prato Chuva$", 13
	.string "Fluxo Areia$", 13
	.string "Pressão$", 13
	.string "Camada Gorda$", 13
	.string "Madrugar$", 13
	.string "Corpo Quente$", 13
	.string "Fuga$", 13
	.string "Olhar Afiado$", 13
	.string "Hiper Corte$", 13
	.string "Pegar$", 13
	.string "Preguiça$", 13
	.string "Pressa$", 13
	.string "Charme$", 13
	.string "Mais$", 13
	.string "Menos$", 13
	.string "Previsão$", 13
	.string "Viscosidade$", 13
	.string "Troca Pele$", 13
	.string "Tenacidade$", 13
	.string "Escama Linda$", 13
	.string "Lodo Líquido$", 13
	.string "Crescimento$", 13
	.string "Combustão$", 13
	.string "Torrente$", 13
	.string "Enxame$", 13
	.string "Cabeça Dura$", 13
	.string "Calor$", 13
	.string "Armadilha$", 13
	.string "Espiritual$", 13
	.string "Fumaça$", 13
	.string "Poder Puro$", 13
	.string "Carapaça$", 13
	.string "Cacofonia$", 13
	.string "Trava Aérea$", 13
