LittlerootTown_BrendansHouse_2F_Text_172E18:: @ 8172E18
	.string "O relógio parou...\p"
	.string "Melhor eu arrumar!$"

LittlerootTown_BrendansHouse_2F_Text_172E4C:: @ 8172E4C
	.string "Mãe: {PLAYER}, como você gosta do seu\n"
	.string "novo quarto??\p"
	.string "Bom! Tudo bem guardado\p"
	.string "Eles terminaram de mover tudo!\n"
	.string "no andar de baixo, também.\p"
	.string "Os movimentos pokémon são tão convenientes!\p"
	.string "Oh, você deve se certificar de\n"
	.string "que tudo está na sua mesa.$"

UnknownString_8172F31: @ 8172F31
	.string "A sua estante é totalmente revistada de\n"
	.string "livros pokémon.\p"
	.string "é a coleção premiada {PLAYER}’s.$"

UnknownString_8172F85: @ 8172F85
	.string "{PLAYER} ligou o pc.$"

LittlerootTown_BrendansHouse_2F_Text_172F9A:: @ 8172F9A
	.string "{PLAYER} abriu o notebook.\p"
	.string "Regra número 1 de aventuras\n"
	.string "Abra o menu com Iniciar.\p"
	.string "Regra número 2 de aventuras\n"
	.string "Registre seu progresso com Save.\p"
	.string "As páginas restantes estão em branco...$"

UnknownString_817303D: @ 817303D
	.string "{PLAYER} olhou mais de perto\n"
	.string "mapa da região de Hoeen.$"

LittlerootTown_BrendansHouse_2F_Text_17306C:: @ 817306C
	.string "É o Gamecube da Nitendo.\p"
	.string "O gameboy está conectado a\n"
	.string "servir como o controlador.$"
