UnknownString_8173A9D: @ 8173A9D
	.string "Espécies e habitat de pokémon...\n"
	.string "Coexistência humana e pokémon...\l"
	.string "Pokémonlogia para iniciantes...\p"
	.string "Está repleto de livros escritos pelo\n"
	.string "professor Birch.$"

LittlerootTown_ProfessorBirchsLab_Text_173B29:: @ 8173B29
	 .string "Hunh? Professor Brich?\p"
     .string "O professor saiu para trabalho de campo.\n"
     .string "Ele não está aqui.\p"
     .string "Deixe-me explicar o que é o\n"
	 .string "trabalho de campos.\p"
     .string "É estudar coisas no ambiente natural,\n"
     .string "nos campos e nas montanhas.\p"
     .string "O professor não gosta de trabalhar no\n"
     .string "laboratório, ele prefere sair e\l"
     .string "estudar a natureza.$"

LittlerootTown_ProfessorBirchsLab_Text_173C88:: @ 8173C88
     .string "O professor não gosta de trabalhar no\n"
     .string "laboratório, ele prefere sair e\l"
     .string "estudar a natureza.$"

LittlerootTown_ProfessorBirchsLab_Text_173D15:: @ 8173D15
     .string "O professor está estudando habitats\n"
     .string "e distribuição dos pokémons.\p"
     .string "{RIVAL} ajuda muito o professor.\n"
     .string "Eles são muito unidos.$"

LittlerootTown_ProfessorBirchsLab_Text_173D94:: @ 8173D94
     .string "Professor Birch: Então, {PLAYER} {KUN}.\p"
     .string "Seu pai me falou sobre você.\p"
     .string "Eu ouvi dizer que você não tem o seu\n"
     .string "próprio POKéMON ainda.\p"
     .string "Mas você lutou de maneira incrível.\p"
     .string "Como agradecimento por me resgatar,\n"
	 .string "gostaria que ficasse com o pokémon\l"
     .string "que você usou.\p"
     .string "{PLAYER} recebeu {STR_VAR_1}!$"

LittlerootTown_ProfessorBirchsLab_Text_173EF8:: @ 8173EF8
     .string "Professor Birch: Aproveitando, o quê\n"
     .string "você acha de apelidar o {STR_VAR_1}?$"

LittlerootTown_ProfessorBirchsLab_Text_173F3D:: @ 8173F3D
     .string "Professor Birch: Batalhando com o\n"
     .string "pokémon, você poderá se tornar\l"
     .string "um grande treinador.\p"
     .string "{RIVAL}, está na Rota 103 estudando\n"
     .string "sobre pokémons selvagens.\p"
     .string "Talvez não seja má idéia para você\n"
     .string "ir ver {RIVAL}. O que você acha?$"

LittlerootTown_ProfessorBirchsLab_Text_174015:: @ 8174015
     .string "Professor Birch: Ótimo!\n"
     .string "{RIVAL} vai ficar feliz.\p"
     .string "Chegue até {RIVAL} para ensinar como\n"
     .string "ser um treinador melhor.$"

LittlerootTown_ProfessorBirchsLab_Text_174075:: @ 8174075
     .string "Professor Birch: Oh, não seja assim.\n"
     .string "Você deve ir até {RIVAL}!$"

LittlerootTown_ProfessorBirchsLab_Text_1740B4:: @ 81740B4
	.string "Professor Birch: {RIVAL} deve estar em\n"
	.string "algum lugar na rota 103.\p"
	.string "Você pode descansar em casa,\n"
	.string "se estiver cansado.$"

LittlerootTown_ProfessorBirchsLab_Text_17411F:: @ 817411F
	.string "Professor Birch: Oh, oi, {PLAYER}{KUN}!\p"
	.string "Eu ouvi dizer que você ganhou de {RIVAL} em\n"
	.string "sua primeira batalha. Muito bem.\p"
	.string "{RIVAL} me ajudou na pesquisa\n"
	.string "durante bastante tempo.\p"
	.string "{RIVAL} tem experiência em batalha.\p"
	.string "Aqui, {PLAYER}{KUN}, eu pedi isso aqui\n"
	.string "para meu ajudante, mas acho que você\l"
	.string "deveria ter a Pokédex.$"

LittlerootTown_ProfessorBirchsLab_Text_17422F:: @ 817422F
	.string "{PLAYER} recebeu a Pokédex!$"

LittlerootTown_ProfessorBirchsLab_Text_174248:: @ 8174248
	.string "Professor Birch: A Pokédex é um\n"
	.string "equipamento de alta tecnologia que\l"
	.string "faz automaticamente um registro\l"
	.string "de qualquer pokémon que você encontre\l"
	.string "ou capture em sua jornada.\p"
	.string "{RIVAL}, vai para todo lugar com ele.\p"
	.string "Sempre que {RIVAL} pega um pokémon,\n"
	.string "ele registra os dados com a Pokédex\l"
	.string "e vai rapidamente atrás de mim para\l"
	.string "me mostrar e estudar o pokémon.$"

LittlerootTown_ProfessorBirchsLab_Text_17436C:: @ 817436C
	.string "Professor Birch: Inúmeros pokémons\n"
	.string "aguardam você lá fora.\p"
	.string "Argh, estou recebendo um chamado para\n"
	.string "fazer trabalho de campo de novo.$"

LittlerootTown_ProfessorBirchsLab_Text_1743D4:: @ 81743D4
	.string "May: Oh, uau, {PLAYER}{KUN}!\n"
	.string "você recebeu a Pokédex, também!\p"
	.string "Que bom! Assim como eu!\n"
	.string "Eu também tenho algo para lhe dar!$"

LittlerootTown_ProfessorBirchsLab_Text_17443D:: @ 817443D
	.string "May: A coisa mais divertida em uma\n"
	.string "aventura é capturar vários pokémon.\p"
	.string "Eu vou olhar em diversos lugares,\n"
	.string "para pegar diferentes pokémons.\p"
	.string "Quando encontrar um pokémon bonito,\n"
	.string "vou usar a Pokébola para capturar!$"

LittlerootTown_ProfessorBirchsLab_Text_1744F0:: @ 81744F0
	.string "Oh? Sua mochila está cheia.$"

LittlerootTown_ProfessorBirchsLab_Text_174505:: @ 8174505
	.string "May: Eu me pergunto. Onde eu deveria\n"
	.string "procurar pokémon depois?$"

LittlerootTown_ProfessorBirchsLab_Text_17453C:: @ 817453C
	.string "Brendan: Huh...\n"
	.string "Você tem a Pokédex, também.\p"
	.string "Bem então, olhe!\n"
	.string "Vou te dar isso.$"

LittlerootTown_ProfessorBirchsLab_Text_17458C:: @ 817458C
	.string "Brendan: É muito divertido ter vários\n"
	.string "pokémons com você.\p"
	.string "Eu vou explorar todos os lugares\n"
	.string "para encontrar diferentes pokémons.\p"
	.string "Se eu encontrar um pokémon legal,\n"
	.string "vou pega-lo com a Pokébola.$"

LittlerootTown_ProfessorBirchsLab_Text_17465B:: @ 817465B
	.string "Hey, sua mochila está cheia.$"

LittlerootTown_ProfessorBirchsLab_Text_174671:: @ 8174671
	.string "BRENDAN: Onde devo procurar meu\n"
	.string "próximo pokémon?$"

LittlerootTown_ProfessorBirchsLab_Text_1746A2:: @ 81746A2
	.string "É uma maquina complicada.\n"
	.string "O professor deve usar pra pesquisas .$"

LittlerootTown_ProfessorBirchsLab_Text_1746E7:: @ 81746E7
	.string "É um PC usado para pesquisa.\n"
	.string "Melhor não mexer nisso.$"

LittlerootTown_ProfessorBirchsLab_Text_174724:: @ 8174724
	.string "São livros sobre pokémon.$"

LittlerootTown_ProfessorBirchsLab_Text_174748:: @ 8174748
	.string "É um livro difícil de ler.$"
