LittlerootTown_BrendansHouse_1F_Text_172429:: @ 8172429
	.string "Mãe: Veja, {PLAYER}?\n"
	.string "Ainda estamos arrumando as caixas.$"

LittlerootTown_BrendansHouse_1F_Text_172453:: @ 8172453
	.string "O pokémon é forte e faz o trabalho\n"
	.string "pesado de mover e limpar.\l"
	.string "Isso é tão coveniente.\p"
	.string "{PLAYER}, seu quarto fica no andar\n"
	.string "superior da casa.\l"
	.string "Olhe como ficou o seu quarto!\p"
	.string "Seu pai comprou um novo relógio\n"
	.string "para o seu quarto.\l"
	.string "Não se esqueça de arruma-lo.$"

LittlerootTown_BrendansHouse_1F_Text_172531:: @ 8172531
	.string "Mãe: {PLAYER}?\p"
	.string "Você não esta interessado em ver seu\n"
	.string "novo quarto?$"

LittlerootTown_BrendansHouse_1F_Text_172574:: @ 8172574
LittlerootTown_MaysHouse_1F_Text_172574:: @ 8172574
	.string "Mãe: {PLAYER}.\p"
	.string "Arrume o relógio do seu quarto, meu bem.$"

LittlerootTown_BrendansHouse_1F_Text_1725A3:: @ 81725A3
	.string "Mãe: Ei! {PLAYER}, {PLAYER}!\n"
	.string "Rápido! Venha!$"

LittlerootTown_BrendansHouse_1F_Text_1725C9:: @ 81725C9
LittlerootTown_MaysHouse_1F_Text_1725C9:: @ 81725C9
	.string "Mãe: Olhe! É o ginásio de Petalburg!\n"
	.string "Talvez seu pai esteja lá!$"

LittlerootTown_BrendansHouse_1F_Text_1725FE:: @ 81725FE
LittlerootTown_MaysHouse_1F_Text_1725FE:: @ 81725FE
	.string "Mãe: Aah... acabou.\p"
	.string "Acho que seu pai estava ali, mas\n"
	.string "perdemos. Que pena.$"

LittlerootTown_BrendansHouse_1F_Text_172644:: @ 8172644
LittlerootTown_MaysHouse_1F_Text_172644:: @ 8172644
	.string "Ah, sim.\n"
	.string "Um dos amigos de seu pai vive\l"
	.string "aqui, na Vila Das Raízes.\p"
	.string "Ele se chama professor Birch.\p"
	.string "Ele mora ao lado, seria bom você\n"
	.string "ir lá e se apresentar à ele.$"

LittlerootTown_BrendansHouse_1F_Text_1726D2:: @ 81726D2
	.string "Mãe: Até logo, meu bem!$"

LittlerootTown_BrendansHouse_1F_Text_1726E7:: @ 81726E7
	.string "Mãe: Você se apresentou ao\n"
	.string "professor Birch?$"

LittlerootTown_BrendansHouse_1F_Text_172717:: @ 8172717
	.string "Mãe: Como vai você, {PLAYER}?\n"
	.string "Você se cansou?\p"
	.string "Eu acho que você deveria descansar um pouco.$"

LittlerootTown_BrendansHouse_1F_Text_17276B:: @ 817276B
	.string "Mãe: Se cuide, meu bem!$"

LittlerootTown_BrendansHouse_1F_Text_172782:: @ 8172782
	.string "Mãe: O seu pai te deu essa insígnia?\p"
	.string "Parabéns, pegue isso como recompensa!$"

LittlerootTown_BrendansHouse_1F_Text_1727CD:: @ 81727CD
	.string "Não precisa se esforçar muito.\n"
	.string "Você pode voltar para casa sempre.\p"
	.string "Se cuide, meu bem!$"

LittlerootTown_BrendansHouse_1F_Text_17281D:: @ 817281D
	.string "Gyao, gyao gyaoh...$"

LittlerootTown_BrendansHouse_1F_Text_172831:: @ 8172831
	.string "Gwagwah gwah...$"

LittlerootTown_BrendansHouse_1F_Text_172841:: @ 8172841
	.string "Entevistador: ...Nós te trouxemos\n"
	.string "noticias do ginásio de Petalburg.$"

UnknownString_817288C: @ 817288C
	.string "É um filme da tv.\p"
	.string "Um homen dançando em um grande piano.\p"
	.string "Melhor ir!$"

UnknownString_81728E3: @ 81728E3
	.string "Instruções dos sapatos de corrida.\p"
	.string "“Segure o botão B enquanto\n"
	.string "estiver com eles para correr.\p"
	.string "Aproveite os sapatos de corrida.”$"

LittlerootTown_BrendansHouse_1F_Text_17298B:: @ 817298B
	.string "Pai: Hm?\p"
	.string "Di,é {PLAYER}!\p"
	.string "Já faz tempo que não vejo você, \n"
	.string "mas você parece...mais forte,de alguma forma\p"
	.string "essa é a empressão que eu recebo.\n"
	.string "Mas seu velho não desistiu ainda!\p"
	.string "Oh, sim, tenho algo para você.\n"
	.string "isso veio pra você de alguém chamado\l"
	.string "senhor.Briney$"

LittlerootTown_BrendansHouse_1F_Text_172A7D:: @ 8172A7D
	.string "Pai: Hm, um Bilhete Para uma Balsa?\p"
	.string "Se eu me lembro,há postas de ferry em\n"
	.string "SLATEPORT e LILYCOVE.\p"
	.string "{PLAYER}, se você tiver ambição como\n"
	.string "treinador,vá para torre de batalha.\p"
	.string "Ensinar-lhe que não existe\n"
	.string "Fim no caminho escolhido pelo treinador.$"

LittlerootTown_BrendansHouse_1F_Text_172B5E:: @ 8172B5E
	.string "Agora devo voltar para o ginásio de Petalburg.\p"
	.string "Mãe, obrigado por cuidar de casa\n"
	.string "enquanto eu estiver fora.$"

LittlerootTown_BrendansHouse_1F_Text_172BBC:: @ 8172BBC
	.string "Mãe: O seu pai...\p"
	.string "ele chega em casa pela primeira vez em um\n"
	.string "enquanto, mas tudo o que ele fala é pokémon\p"
	.string "ele deveria relaxar e ficar mais.$"

UnknownString_8172C50: @ 8172C50
	.string "Nós lhe trazemos um boletim de notícias especial.\p"
	.string "Recebemos relatórios de um voador azul.\n"
	.string "pokémons em vários locais de Hoenn.\p"
	.string "A identidade desse pokémon não tem.\n"
	.string "Ainda não foi determinado.\p"
	.string "Agora devolvemos você ao seu regular\n"
	.string "apresentaçao do filme.$"

UnknownString_8172D30: @ 8172D30
	.string "Nós lhe trazemos um boletim de notícias especial.\p"
	.string "Recebemos relatórios de um voador vermelho.\n"
	.string "pokémons em vários locais de Hoenn.\p"
	.string "A identidade desse pokémon não tem.\n"
	.string "Ainda não foi determinado.\p"
	.string "Agora devolvemos você ao seu regular\n"
	.string "apresentaçao do filme.$"

UnknownString_8172E0F: @ 8172E0F
	.string "Gau gau!$"
