LittlerootTown_Text_16A7C9:: @ 816A7C9
	.string "Mãe: {PLAYER}, chegamos!\p"
	.string "Deve ser cansativo viajar com nossas\n"
	.string "coisas balançando no caminhão.\p"
	.string "Bem, aqui é a Vila Das Raízes.\p"
	.string "Você gostou?\n"
	.string "Essa é nossa nova casa!\p"
	.string "Tem uma sensação peculiar, mas parece\n"
	.string "ser um lugar fácil de viver, não acha?\p"
	.string "Agora, você tem seu próprio quarto.\n"
	.string "Vamos entrar.$"

LittlerootTown_Text_16A8EE:: @ 816A8EE
	.string "Mãe: Espera, {PLAYER}!$"

LittlerootTown_Text_16A8FD:: @ 816A8FD
	.string "Mãe: {PLAYER}! {PLAYER}! Você se\n"
	.string "apresentou ao Professor Birch?\p"
	.string "Olha! Que pokémon adorável.\n"
	.string "Você ganhou do professor Birch?\p"
	.string "Você realmente parece com o seu pai.\p"
	.string "Leve isso! Quando sair para uma\n"
	.string "aventura, você poderá ir mais rápido.\p"
	.string "Espero que ajude em sua aventura.$"

LittlerootTown_Text_16AA32:: @ 816AA32
	.string "{PLAYER} trocou os sapatos por\n"
	.string "sapatos de corrida.$"

LittlerootTown_Text_16AA5C:: @ 816AA5C
	.string "Mãe: {PLAYER}, esses sapatos vieram\n"
	.string "com instruções.\p"
	.string "“Segure o botão B enquanto\n"
	.string "estiver com eles para correr.\p"
	.string "Aproveite os sapatos de corrida.”$"

LittlerootTown_Text_16AB10:: @ 816AB10
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "E pensar que você tem seu próprio\n"
	.string "pokémon agora...\l"
	.string "Seu pai ficará muito feliz.\p"
	.string "... Mas seja cuidadoso.\n"
	.string "Se acontecer algo, volte para casa.\p"
	.string "Tome cuidado!$"

LittlerootTown_Text_16AC00:: @ 816AC00
	.string "Se você usar o computador, poderá\n"
	.string "armazenar itens e pokémon.\p"
	.string "O poder da ciência é surpreendente!$"

LittlerootTown_Text_16AC56:: @ 816AC56
	.string "O Professor Birch passa dias no seu\n"
	.string "laboratório estudando, e só sai para\l"
	.string "fazer pesquisa de campo.\p"
	.string "Quando o professor vai para casa?$"

LittlerootTown_Text_16ACEB:: @ 816ACEB
	.string "Um pokémon pode te atacar, se você\n"
	.string "entrar na grama alta.$"

LittlerootTown_Text_16AD3C:: @ 816AD3C
	.string "É perigos ir para essa rota se você\n"
	.string "não possuir pokémon.$"

LittlerootTown_Text_16AD82:: @ 816AD82
	.string "Alguém está gritando.\p"
	.string "O que vamos fazer?\n"
	.string "Alguém tem que ajudar...$"

LittlerootTown_Text_16ADF2:: @ 816ADF2
	.string "Nossa, estou tão feliz por você ter\n"
	.string "ajudado o professor.$"

LittlerootTown_Text_16AE25:: @ 816AE25
	.string "Você vai capturar pokémons?\n"
	.string "Então, boa sorte!$"

LittlerootTown_Text_16AE50:: @ 816AE50
	.string "Vila Das Raízes\n"
	.string "“A vila que não pode ser sombreada.”$"

LittlerootTown_Text_16AE87:: @ 816AE87
	.string "Laboratório do professor Birch$"

LittlerootTown_Text_16AEA1:: @ 816AEA1
	.string "Casa do {PLAYER}$"

LittlerootTown_Text_16AEAC:: @ 816AEAC
	.string "Casa do professor Birch$"
